# Generated by Django 3.2.23 on 2024-04-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240408_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_day',
            field=models.IntegerField(default=31, verbose_name='決算日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_month',
            field=models.IntegerField(default=3, verbose_name='決算月'),
        ),
    ]
