# Generated by Django 3.2.23 on 2024-03-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shiwake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='サンプル項目1 文字列')),
            ],
        ),
    ]
