# Generated by Django 3.2.23 on 2024-03-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanjo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taishaku', models.BooleanField(default=True, help_text='借方ならTrue', verbose_name='貸借')),
                ('kanjo_kamoku', models.CharField(max_length=20, verbose_name='勘定科目')),
                ('amount', models.IntegerField(verbose_name='金額')),
            ],
            options={
                'verbose_name': '勘定',
                'verbose_name_plural': '勘定',
            },
        ),
        migrations.CreateModel(
            name='Shiwake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiwake_date', models.DateField(blank=True, null=True, verbose_name='日付')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='作成時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '仕訳',
                'verbose_name_plural': '仕訳',
            },
        ),
    ]
