# Generated by Django 3.2.23 on 2024-03-15 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shiwake', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiwake',
            name='sample_1',
        ),
        migrations.AddField(
            model_name='shiwake',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='作成時間'),
        ),
        migrations.AddField(
            model_name='shiwake',
            name='owner',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shiwake_owner', to=settings.AUTH_USER_MODEL, verbose_name='所有者'),
        ),
        migrations.AddField(
            model_name='shiwake',
            name='shiwake_date',
            field=models.DateField(blank=True, null=True, verbose_name='日付'),
        ),
        migrations.AddField(
            model_name='shiwake',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='更新時間'),
        ),
    ]
