# Generated by Django 3.2.23 on 2024-03-27 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
        ('shiwake', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanjo',
            name='kanjo_kamoku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_kanjo_kamokus', to='app.masterkanjokamoku', verbose_name='勘定科目'),
        ),
    ]
