# Generated by Django 3.2.23 on 2024-03-15 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shiwake', '0002_auto_20240315_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiwake',
            options={'verbose_name': '仕訳', 'verbose_name_plural': '仕訳'},
        ),
    ]
