# Generated by Django 3.2.23 on 2024-03-15 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shiwake', '0003_alter_shiwake_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kanjo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanjo_kamoku', models.CharField(max_length=20, verbose_name='勘定科目')),
                ('amount', models.IntegerField(verbose_name='金額')),
                ('shiwake', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='shiwake', to='shiwake.shiwake', verbose_name='仕訳')),
            ],
        ),
    ]
