# Generated by Django 3.2.23 on 2024-03-15 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shiwake', '0004_kanjo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kanjo',
            options={'verbose_name': '勘定', 'verbose_name_plural': '勘定'},
        ),
        migrations.AlterField(
            model_name='kanjo',
            name='shiwake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanjos', to='shiwake.shiwake', verbose_name='仕訳'),
        ),
    ]
