# Generated by Django 3.2.23 on 2024-03-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiwake', '0005_auto_20240315_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanjo',
            name='taishaku',
            field=models.BooleanField(default=True, help_text='借方ならTrue', verbose_name='貸借'),
        ),
    ]
