# Generated by Django 3.2.23 on 2024-03-28 06:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shiwake', '0005_alter_shiwake_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiwake',
            name='created_at',
            field=models.DateTimeField(editable=False, verbose_name='作成時間'),
        ),
        migrations.AlterField(
            model_name='shiwake',
            name='owner',
            field=models.ForeignKey(default=0, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='shiwake_owner', to='users.user', verbose_name='所有者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shiwake',
            name='shiwake_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 28, 6, 6, 29, 141030, tzinfo=utc), verbose_name='日付'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shiwake',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 28, 6, 6, 29, 141030, tzinfo=utc), editable=False, verbose_name='更新時間'),
            preserve_default=False,
        ),
    ]
