# Generated by Django 3.2.23 on 2024-03-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_name', models.CharField(max_length=20, verbose_name='デッキ名')),
                ('public_flag', models.BooleanField(default=False, verbose_name='全体公開')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='作成時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': 'デッキ',
                'verbose_name_plural': 'デッキ',
            },
        ),
    ]
