# Generated by Django 3.2.23 on 2024-04-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterkanjokamoku',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='勘定科目名'),
        ),
    ]
